### ISSUE TITLE
caching headers added independently of status code

### ISSUE THREAD

**Issue by dedominicisfa** [twiebe/Flask-CacheControl#2]
When we apply the cache_for decorator to a flask_response, the caching header is applied even if we abort the request with the flask abort function or if we answer with a non 200 code (see 400, 500, 504 as example). Or we should configure for which status codes to return the caching headers, or the decorator itself shouldn't add them if the response has an error status code.

**Comment by twiebe** [comment]
Thanks for reporting. @dedominicisfa 

PR #4 allows for making the cache control headers status code specific and also does so by default.

These changes have been released in 0.2.0. Please note that py2 support has been dropped with this release.
