### ISSUE TITLE
Add support for Vary

### ISSUE THREAD

**Issue by stefano-xy** [twiebe/Flask-CacheControl#6]
Could you please add support for the `Vary` header? It's not strictly the `Cache-Control` header, but it's related to caching.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary

Thank you.

**Comment by twiebe** [comment]
Hey @ragazzojp, thanks for the request.

I've looked into it. To me it looks like a viable implementation would
* always set `Vary: *` where the `@dont_cache()` decorator is used
* set `Vary:` to any number of headers where specified in an optional `vary` list of the `@cache()` decorator. F.e. 
```python
@cache(max_age=3600, public=True, vary=['Accept', 'User-Agent'])
def foo():
...
```

What do you think?

**Comment by stefano-xy** [comment]
Hi, thanks for helping me with `Vary`. I think there's no point of setting `Vary: *` in case of `@dont_cache`, by the way `*` is a dangerous setting, I would prefer you don't do it. Regarding `@cache`, I think what you propose is a good and elegant solution. Add it to `@cache_for` as well, please.

**Comment by twiebe** [comment]
Hey @ragazzojp,

finally took the time to work on release `0.3.0`, which includes support for the `Vary` header are outlined here. Hope it works for you. Otherwise please ping.

**Comment by stefano-xy** [comment]
I confirm it works as intended. Sorry for the late response.
