### ISSUE TITLE
Consider 3xx responses as successfull and cache them

### ISSUE THREAD

**Issue by stefano-xy** [twiebe/Flask-CacheControl#7]
Cache headers are applied only to successful responses. In the case, this means HTTP responses codes >= 200 and < 300. I think 3xx responses should also be considered successful responses, and therefore included in the default behavior. I would still not cache 1xx responses and client (4xx) and error (5xx) responses.

For example, CloudFront caches 3xx responses: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-3xx-status-codes.html

**Comment by twiebe** [comment]
Thanks for the input @ragazzojp and the pointer to the cloudfront docs.

The idea of not applying caching headers to `3xx` responses **by default** is that some responses in the `3xx` range have their expiration given by the status code itself. F.e.
* `301` and `308`, by nature, are permanent.
* `302` and `307`, by nature, are temporary. (though w/o any specific limitation)
* `304` are simply a confirmation that the cached content is still valid for the originally given criteria.

So, while the cloudfront docs confirm that caching headers for `3xx` responses would be regarded by their CDN, and certainly by browsers, from the point of view of the web/api developer, who is the user of this lib, it might still be unexpected to apply them to `304`, `301` or `308` responses - **by default**. 

Does that make sense to you? Would you agree?

**Comment by stefano-xy** [comment]
It's an interesting but slippery discussion. I think the tricky part is separating caching of responses, whatever they are, from semantic of some responses that seem to contain information that is permanent or temporary.

Just for the sake of discussion, suppose a resource is permanently relocated to X by a 301 or 308. Browsers would look up X directly without trying the old url. Someone could ther further relocate the resource to Y, so that both the original url and X now return 301 or 308 to Y. If the former responses, not their semantic, don't expire, old clients will always forward to X and never discover Y. Or maybe I'm confused.

Anyway responses are given back to the browsers, the CDN doesn't follow redirects for them, controlling when and how these should be cached should be independent of the semantic of the redirect itself. I'd say it's safer choice than applying only to some 3xx code. Also remember than Flask can be used to build REST APIs, so the client may not be a browser.

Back to the original question, it's definitely fine tuning for power users and who need very precise control of what happens. I would not enable it by default, but provide a setting or a class similar to the one that applies the cache to 2xx only, but in this case to the whole 3xx range.

Just to say, someone may want to control caching of 404 and similar. Clearly a corner case and it shouldn't be the default case, but it should be still possible. 3xx is more reasonable. 5xx is a nonsense.

I need to control caching of a 302 with the addition of `Vary` headers, just to say ...

**Comment by twiebe** [comment]
Hey @ragazzojp,

`0.3.0` now contains the `ResponseIsSuccessfulOrRedirect` evaluator that can be used with `only_if=ResponseIsSuccessfulOrRedirect`. I hope it works for you.

BTW: be sure to check the changelog. The release has other improvements and does have breaking changes.
