### ISSUE TITLE
Simplify implementation with `flask.after_this_request`

### ISSUE THREAD

**Issue by soxofaan** [twiebe/Flask-CacheControl#8]
Hi, I was looking into a solution for setting Cache-Control headers in Flask, preferably with view function decorators and stumbled on this project. I had a look into your implementation and was a bit overwhelmed by the complexity and layers.
After some more looking around I cooked up my own version, illustrated here:
https://gist.github.com/soxofaan/4a646f0ac24208cd097c7ab6ea21cc85
It's just around 40 LOC, one single function (the decorator), no need for something like `init_app`, no use of pseudo-globals like `flask.g` or other hidden coupling, just a direct `flask.after_this_request` call. Feature-wise it comes very close to what Flask-CacheControl already supports I think.

I'm putting it here if somebody would be interested.
Or it could serve as inspiration for a next version of Flask-CacheControl

**Comment by twiebe** [comment]
Tbh, I'm completely puzzled by why I didn't take the short path of directly registering response modifiers via  `flask.after_this_request` from the start. Not a clue.

Thanks a lot @soxofaan for pointing it out. Removing the `g` detour made things a lot simpler. It's part of the `0.3.0` release that just went out.

Again, thanks!

**Comment by soxofaan** [comment]
Great! And already with a new release? That's a fast response time :smile:
